"""empty message

Revision ID: 27e02c866467
Revises: eaeac91f6073
Create Date: 2022-05-25 13:11:37.665085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e02c866467'
down_revision = 'eaeac91f6073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'cool')
    op.drop_column('animal', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('animal', sa.Column('cool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
