"""empty message

Revision ID: eaeac91f6073
Revises: ba8c5baae3f9
Create Date: 2022-05-25 13:05:14.480032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaeac91f6073'
down_revision = 'ba8c5baae3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('animal', sa.Column('size_cm', sa.Integer(), nullable=True))
    op.add_column('animal', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('animal', sa.Column('price', sa.Float(precision=2), nullable=False))
    op.add_column('animal', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_column('animal', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('animal', 'created_on')
    op.drop_column('animal', 'price')
    op.drop_column('animal', 'image')
    op.drop_column('animal', 'size_cm')
    op.drop_column('animal', 'name')
    # ### end Alembic commands ###
